### ISSUE TITLE
hostname in certificate didn't match: <westus.api.cognitive.microsoft.com> != <*.cognitiveservices.azure.com> OR <*.cognitiveservices.azure.com>

### ISSUE THREAD

**Issue by jatin-lakhani** [Microsoft/Cognitive-Face-Android#52] opened 2019-02-18 13:09 UTC

**Comment by jatin-lakhani** [comment] 2019-02-18 13:10
Face detection api gives error in samsung devices. It works with other device but getting error in samsung device only

The following error shows in log :
hostname in certificate didn't match: <westus.api.cognitive.microsoft.com> != <*.cognitiveservices.azure.com> OR <*.cognitiveservices.azure.com>

please help me on this.

**Comment by vernazza** [comment] 2019-02-23 12:46
Same problem here, with error
 javax.net.ssl.SSLException: hostname in certificate didn't match: <eastus2.api.cognitive.microsoft.com> != <*.cognitiveservices.azure.com> OR <*.cognitiveservices.azure.com>

**Comment by vernazza** [comment] 2019-02-25 10:46
The problem is due to a change in the certificates on MS side.
The library uses a deprecated & outdated org.apache httpClient that doesn't support SNI headers. (see #50)

**Comment by lebronJ** [comment] 2019-03-11 10:20
Thanks @vernazza for the contribution, with that PR #53 merged, this should be fixed. Feel free to reopen this if you still meet similar problems.

**Closed by lebronJ** 2019-03-11 10:20 UTC
